export type ServiceCategory = {
  id: string;
  name: string;
  suggestedCategories: string[];
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "exterior",
    name: "외장 시공 (간판·외벽)",
    suggestedCategories: [
      "간판 제작",
      "간판 시공·설치",
      "전기·배선 공사",
      "옥외광고물 허가",
      "디자인비",
      "외벽 도장",
      "외벽 패널",
      "외벽 방수",
      "비계 설치",
      "폐기물 처리",
    ],
  },
  {
    id: "demolition",
    name: "철거",
    suggestedCategories: [
      "인건비",
      "바닥 철거",
      "벽 철거",
      "가구 철거",
      "주방 철거",
      "욕실 철거",
      "천장 철거",
      "창호 철거",
      "폐기물 처리",
      "공과잡비",
    ],
  },
  {
    id: "interior",
    name: "인테리어 (집·상업공간)",
    suggestedCategories: [
      "철거",
      "목공",
      "욕실",
      "타일",
      "도배",
      "장판·바닥재",
      "조명·전기",
      "도장·페인트",
      "가구·붙박이",
      "창호·샤시",
      "필름",
      "공과잡비",
    ],
  },
  {
    id: "bath_kitchen",
    name: "욕실/주방 리모델링",
    suggestedCategories: [
      "철거",
      "욕실",
      "주방",
      "타일",
      "도기·수전",
      "가구·수납",
      "가전 설치",
      "방수",
      "조명·환풍",
      "공과잡비",
    ],
  },
  {
    id: "wallpaper_floor",
    name: "도배·장판",
    suggestedCategories: [
      "실크 도배",
      "합지 도배",
      "천장 도배",
      "초배지",
      "장판",
      "강마루",
      "데코타일",
      "가구 이동",
      "폐기물 처리",
    ],
  },
  {
    id: "moving",
    name: "이사",
    suggestedCategories: [
      "가정 이사",
      "사업장 이사",
      "사다리차",
      "포장 서비스",
      "보관 이사",
      "추가 짐",
      "보양",
      "폐기물 처리",
    ],
  },
  {
    id: "cleaning",
    name: "청소",
    suggestedCategories: [
      "입주 청소",
      "거주 청소",
      "사업장 청소",
      "준공 청소",
      "베란다 추가",
      "화장실 추가",
      "새집증후군 제거",
      "곰팡이 제거",
      "폐기물 처리",
      "출장비",
    ],
  },
  {
    id: "etc",
    name: "기타",
    suggestedCategories: [
      "시공비",
      "자재비",
      "인건비",
      "출장비",
      "운반비",
      "폐기물 처리",
      "공과잡비",
      "부가세",
    ],
  },
];
